In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[1, 16]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[3, 27], [1, 16], [20, 27], [9, 23, 17], [14, 7, 7], [14, 27], [11, 7, 11], [24, 8], [24, 14], [13, 14]]


In [5]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 3 27  0  0]
 [ 1 16  0  0]
 [20 27  0  0]
 [ 9 23 17  0]
 [14  7  7  0]
 [14 27  0  0]
 [11  7 11  0]
 [24  8  0  0]
 [24 14  0  0]
 [13 14  0  0]]


In [6]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
model.fit(X, y, epochs=50, verbose=0)

In [10]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 151ms/step - loss: 0.6148 - accuracy: 0.9000


0.8999999761581421

In [11]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [14]:
weights[3]

array([ 0.01075194,  0.0991952 , -0.02878061, -0.06056595,  0.09898761],
      dtype=float32)

In [15]:
weights[1]

array([ 0.04955684,  0.05692954, -0.00193802, -0.04158225,  0.04217995],
      dtype=float32)

In [16]:
weights[27]

array([-0.08977683,  0.06283474,  0.01177273, -0.01944235,  0.00738959],
      dtype=float32)